[package]
name = "raytracer"
version = "0.1.0"
authors = ["emma"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.0"
cgmath = "0.17.0"
image = "0.22.3"
minifb = "0.12"
rand = "0.7.0"
rayon = "1.1.0"
